server:
  port: 8080
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  user: "xdooria"
  password: "securepassword123"
  dbname: "xdooria_db"

logger:
  level: "trace"  # 无效的日志级别 (oneof=debug info warn error)
  format: "json"
