server:
  port: 8080
  # host 字段缺失（required）

database:
  host: "localhost"
  port: 5432
  user: "xdooria"
  password: "securepassword123"
  dbname: "xdooria_db"

logger:
  level: "info"
  format: "json"
