apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://xiaojia-prometheus-prod:9090
    isDefault: true
    editable: false

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://xiaojia-jaeger-query:16686
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://xiaojia-jaeger-es:9200
    database: jaeger-span-*
    editable: false
    jsonData:
      timeField: startTime
      esVersion: 8.0.0
