services:
  redis-redlock-1:
    image: redis:7.4-alpine
    container_name: xdooria-redis-redlock-1
    ports:
      - "18001:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - redis-redlock-net

  redis-redlock-2:
    image: redis:7.4-alpine
    container_name: xdooria-redis-redlock-2
    ports:
      - "18002:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - redis-redlock-net

  redis-redlock-3:
    image: redis:7.4-alpine
    container_name: xdooria-redis-redlock-3
    ports:
      - "18003:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly no
      --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - redis-redlock-net

networks:
  redis-redlock-net:
    driver: bridge
