log:
  level: debug
  format: console
  enable_console: true

server:
  name: login-server
  address: :50051
  network: tcp

jwt:
  secret_key: "xdooria-secret-key-123456"
  algorithm: HS256
  expires_in: 24h

framer:
  enable_encrypt: false # 开发环境先关闭加密方便调试
  enable_compress: false
  compress_min_bytes: 1024