global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'example-app'
    static_configs:
      - targets: ['app:9090']
        labels:
          service: 'observability-example'
          environment: 'docker'
